# -*- coding: utf-8 -*-
"""3D flat belt conveyor

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttPZIYvM_mC2ZtKBNqqAhYKIO8P4ORKW
"""

import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
#create figure
fig=plt.figure(figsize=(10,6)) #figsize=inches(width,height)
ax=fig.add_subplot(111,projection='3d') #111=1row,1column,1subplot
#define
belt_x=np.linspace(0,10,100)
belt_y=np.zeros_like(belt_x)
belt_z=np.zeros_like(belt_x)
idler_x=np.linspace(1,10,3)
idler_y=np.zeros_like(idler_x)
idler_z=np.zeros_like(idler_x)
ax.plot(belt_x,belt_y,belt_z, color='black', linewidth=3, label= "Flat belt")
ax.scatter(idler_x,idler_y,idler_z, color='red',s=100,label="Idler")
#label & title
ax.set_xlabel("X position (m)")
ax.set_ylabel("Y position (m)")
ax.set_zlabel("Z position (m)")
ax.set_title("3D flat conveyor system")
ax.legend()
ax.grid()
ax.view_init(elev=20,azim=30)
plt.show()

